#!/bin/bash

declare -A FAILED_TESTS
SIMULATOR="${1:-unicorn}"
TESTS="page_fault piping simply_execve simply_exit simply_fork simply_write waiting"

FAILED_TESTS[$SIMULATOR]+=""
for file in $TESTS; do
    echo "--------------------------------"
    echo "Running test: $file"
    echo "--------------------------------"
    ./tests/$file $SIMULATOR
    if [[ $? -ne 0 ]]; then
        FAILED_TESTS[$SIMULATOR]+="$file "
    fi
    echo ""
done

for key in "${!FAILED_TESTS[@]}"; do
    FAILED="${FAILED_TESTS[$key]}"
    echo "Simulator: $key"
    if [[ -z "$FAILED" ]]; then
        echo "    All tests passed :)"
    else
        echo "    Some tests failed:"
        echo "    $FAILED"
    fi
    echo ""
done

