#!/usr/bin/expect

spawn python -u src/kite/__main__.py binaries/simply_exit --simulator [lindex $argv 0] --debug

expect "0x8000001c - event: page fault - page not present"
expect "0x8000001c -        fault_addr: 0x8000001c"
expect "0x8000001c -        fault_pc: 0x8000001c"
expect "0x80000004 - event: page fault - page not present"
expect "0x80000004 -        fault_addr: 0x8001fffc"
expect "0x80000004 -        fault_pc: 0x80000004"
expect eof
