#!/usr/bin/expect

spawn python -u src/kite/__main__.py binaries/simply_exit --simulator [lindex $argv 0] --log-to-stdout

expect "event: page fault - page not present"
expect "fault_addr:"
expect "fault_pc:"
expect eof
