#!/usr/bin/expect

spawn python -u src/kite/__main__.py binaries/piping --simulator [lindex $argv 0] --log-to-stdout

expect "event: syscall - pipe"
expect "event: syscall - fork"
expect "event: syscall - write"
expect eof
