#!/usr/bin/expect

spawn python -u src/kite/__main__.py binaries/simply_fork --simulator [lindex $argv 0] --log-to-stdout

expect "event: syscall - open"
expect "open file_name: file.log"
expect "event: syscall - write"
expect eof
