#!/usr/bin/expect

spawn python -u src/kite/__main__.py binaries/simply_write --simulator [lindex $argv 0] --log-to-stdout

expect "event: syscall - openat"
expect "open file_name:"
expect "event: syscall - write"
expect eof
