#!/usr/bin/expect

spawn python -u src/kite/__main__.py binaries/simply_fork --simulator [lindex $argv 0] --sysroot binaries --log-to-stdout

expect "event: syscall - fork"
expect "event: syscall - execve"
expect eof
