#!/usr/bin/expect

spawn python -u src/kite/__main__.py binaries/simply_execve --simulator [lindex $argv 0] --sysroot binaries --log-to-stdout

expect "event: syscall - execve"
expect "execve file_name: simply_exit"
expect eof
