#!/usr/bin/expect

spawn python -u src/kite/__main__.py binaries/waiting --simulator [lindex $argv 0] --log-to-stdout

expect "event: syscall - pipe"
expect "event: syscall - fork"
expect "event: syscall - wait"
expect "event: syscall - exit"
expect "event: syscall - exit"
expect eof
