name: Hello World Action

on:
  push:
    branches:
      - '**'

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Run tests
      run: |
        pip install -r requirements.txt
        mkdir sysroot
        echo "print('Hello world')" > sysroot/script.lua
        python -u -m kite lua script.lua
